# This is a QCR ROS debianising pipeline for amd64, arm64 and arm32
# Assumes the latest ubuntu for running the job (with ROS noetic (temp))
name: release-build-pipeline

# Controls when the workflow will run
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release-build-action:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: 'amd64'
          - arch: 'arm64'
          - arch: 'arm32'
    name: Release-Build-Pipeline
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository into a workspace/src folder 
      - name: Checkout Package
        uses: actions/checkout@v2
        with:
          path: ws/src/${{ github.event.repository.name }}
      - name: Setup QEMU dependency
        uses: docker/setup-qemu-action@v1
      # Builds your packages within a different architectures (in matrix above)
      - name: Run Release Workflow
        id: build
        uses: qcr/ros-debian-release-action@master
        with:
          architecture: ${{ matrix.arch }}
      # Upload the debian binaries to your repo with the current tag
      - name: Upload Binaries to Release
        uses: suddrey-qut/upload-release-action@master
        id: upload
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ steps.build.outputs.debian-files }}
          tag: ${{ github.ref }}
      # Notifies QCR for download
      - name : Notify QCR
        uses: suddrey-qut/invoke-qcr-hook@master
        with:
          ref: ${{ github.ref }}
          repo: ${{ github.repository }}
          files: ${{ steps.upload.outputs.browser_download_urls }}
          packages: ${{ steps.build.outputs.packages }}
